# Generated by Django 4.1.4 on 2022-12-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('channel_url', models.URLField(blank=True, null=True)),
                ('registrant_num', models.IntegerField(blank=True, null=True)),
                ('good_num', models.IntegerField(blank=True, null=True)),
                ('video_num', models.IntegerField(blank=True, null=True)),
                ('publishedat', models.DateTimeField(blank=True, null=True)),
                ('video_url1', models.URLField(blank=True, null=True)),
                ('video_url2', models.URLField(blank=True, null=True)),
                ('video_url3', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
