# Generated by Django 4.1.4 on 2022-12-29 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255)),
                ('channel_id', models.CharField(max_length=24)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ChannelID',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Log',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title1', models.CharField(blank=True, max_length=255, null=True)),
                ('video_url1', models.URLField(blank=True, null=True)),
                ('video_thumbnail1', models.URLField(blank=True, null=True)),
                ('video_view_count1', models.IntegerField(blank=True, null=True)),
                ('video_published_at1', models.CharField(blank=True, max_length=11, null=True)),
                ('video_title2', models.CharField(blank=True, max_length=255, null=True)),
                ('video_url2', models.URLField(blank=True, null=True)),
                ('video_thumbnail2', models.URLField(blank=True, null=True)),
                ('video_view_count2', models.IntegerField(blank=True, null=True)),
                ('video_published_at2', models.CharField(blank=True, max_length=11, null=True)),
                ('video_title3', models.CharField(blank=True, max_length=255, null=True)),
                ('video_url3', models.URLField(blank=True, null=True)),
                ('video_thumbnail3', models.URLField(blank=True, null=True)),
                ('video_view_count3', models.IntegerField(blank=True, null=True)),
                ('video_published_at3', models.CharField(blank=True, max_length=11, null=True)),
                ('video_title4', models.CharField(blank=True, max_length=255, null=True)),
                ('video_url4', models.URLField(blank=True, null=True)),
                ('video_thumbnail4', models.URLField(blank=True, null=True)),
                ('video_view_count4', models.IntegerField(blank=True, null=True)),
                ('video_published_at4', models.CharField(blank=True, max_length=11, null=True)),
                ('video_title5', models.CharField(blank=True, max_length=255, null=True)),
                ('video_url5', models.URLField(blank=True, null=True)),
                ('video_thumbnail5', models.URLField(blank=True, null=True)),
                ('video_view_count5', models.IntegerField(blank=True, null=True)),
                ('video_published_at5', models.CharField(blank=True, max_length=11, null=True)),
                ('video_title6', models.CharField(blank=True, max_length=255, null=True)),
                ('video_url6', models.URLField(blank=True, null=True)),
                ('video_thumbnail6', models.URLField(blank=True, null=True)),
                ('video_view_count6', models.IntegerField(blank=True, null=True)),
                ('video_published_at6', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'Video',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255, null=True)),
                ('channel_url', models.URLField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('subscriber_count', models.IntegerField(blank=True, null=True)),
                ('video_count', models.IntegerField(blank=True, null=True)),
                ('view_count', models.IntegerField(blank=True, null=True)),
                ('published_at', models.CharField(blank=True, max_length=11, null=True)),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channnel_id', to='youtubeapp.channelid')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='youtubeapp.video')),
            ],
            options={
                'db_table': 'Channel',
                'ordering': ['subscriber_count'],
            },
        ),
    ]
