# Generated by Django 4.1.4 on 2022-12-28 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YoutubeData',
            new_name='Data',
        ),
        migrations.CreateModel(
            name='ChannelID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=24)),
                ('channel_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youtubeapp.data')),
            ],
        ),
    ]
