# Generated by Django 4.1.4 on 2022-12-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0002_alter_channelid_channel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelid',
            name='category',
            field=models.CharField(choices=[('1', 'APEX LEGENDS'), ('2', 'CLASH ROYALE'), ('3', 'FORTNITE'), ('4', 'VALORANT'), ('5', 'SUPER SMASH BROS'), ('6', 'STREAMER')], max_length=255),
        ),
        migrations.AlterField(
            model_name='channelid',
            name='channel_name',
            field=models.CharField(max_length=255),
        ),
    ]
