# Generated by Django 4.1.4 on 2022-12-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0003_alter_channelid_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='subscriber_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='video_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='view_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_view_count1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_view_count2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_view_count3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_view_count4',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_view_count5',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_view_count6',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
